# Ciencia de Datos II (GES0132) — UCA
## Trabajo Práctico N°1: Exploración Inical de Datos de Negocios con Pandas
**Docente:** Esp. Prof. Diego Vidal Silva (@diegovidalsilva)
#####**Semana 1:** Trabajo Virtual Asincrónico

### Objetivos:
· Configurar y verificar el entorno virtual en la nube (Google Colab)
#####· Importar la libreria especializada 'pandas'.
#####· Cargar un dataset real desde un repositorio web (*Open Data*)
#####· Aplicar inspección estructural: *shape*, *columns*, *head()* y *describe()*
#####· Formular conclusiones de negocio sobre el fenómeno analizado.

### ■ Paso 1: Importación de librerias esenciales

In [57]:
import pandas as pd
import numpy as np

print('Entorno configurado correctamente')
print(f'Versión de pandas instalada: {pd.__version__}')

Entorno configurado correctamente
Versión de pandas instalada: 2.2.2

### ■ Paso 2: Carga del Dataset desde Fuente Remota (Open Data)
Cargaré un dataset a mi gusto (es sobre el rendimiento de jugadores de la Copa del Mundo 2026).

In [58]:
# Carga de dataset remoto desde GitHub
url_dataset = 'https://raw.githubusercontent.com/Gatogato05/Ciencia-de-Datos-II/refs/heads/main/Semana%201/fifa_world_cup_2026_player_performance.csv'

df = pd.read_csv(url_dataset)
print(f"Dataset cargado exitosamente en el DataFrame 'df' desde GitHub:\n{url_dataset}")

Dataset cargado exitosamente en el DataFrame 'df' desde GitHub:
https://raw.githubusercontent.com/Gatogato05/Ciencia-de-Datos-II/refs/heads/main/Semana%201/fifa_world_cup_2026_player_performance.csv

### ■ Paso 3: Inspección Estructural del DataFrame
Determinamos las dimensiones de la tabla (filas u observaciones x columnas o variables).

In [59]:
# Inspección de forma (filas, columnas)
filas, columnas = df.shape
print(f'Dimensiones: {filas} filas y {columnas} columnas.\n')

# Lista de variables disponibles
print('Variables en el dataset:')
print(df.columns.tolist())

Dimensiones: 54600 filas y 75 columnas.

Variables en el dataset:
['player_id', 'player_name', 'age', 'nationality', 'team', 'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot', 'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium', 'city', 'opponent_team', 'tournament_stage', 'match_result', 'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists', 'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa', 'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy', 'dribbles_attempted', 'successful_dribbles', 'crosses', 'successful_crosses', 'tackles', 'interceptions', 'clearances', 'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries', 'defensive_actions', 'fouls_committed', 'fouls_suffered', 'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage', 'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves', 'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh', 'accelerations', 'decelerations', 'stamina_score', 'player_rating', 'performance_score', 'offensive_contribution', 'defensive_contribution', 'possession_impact', 'pressure_resistance', 'creativity_score', 'consistency_score', 'clutch_performance_score', 'total_goals_tournament', 'total_assists_tournament', 'total_minutes_tournament', 'player_of_match_awards', 'tournament_rating']

### ■ Paso 4: Muestra de Registros Iniciales
Visualizamos los primeros 5 registros de la tabla para entender el formato de los datos.

In [60]:
# Muestra inicial de las primeras 5 observaciones
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.10,44.20,55.90,42.00,51.80,0,0,242,0,5.80
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.50,38.20,43.70,31.10,52.70,0,3,342,0,5.50
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.30,99.00,99.00,83.40,54.80,1,1,245,0,8.40
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.20,19.80,42.30,40.90,78.50,5,3,422,0,6.70
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.20,44.10,33.50,60.00,56.60,0,0,440,0,5.70

### ■ Paso 5: Diagnóstico de Tipos de Datos y Valores Nulos
Analizamos si las columnas son numéricas o de texto y verificamos la presencia de datos faltantes.

In [61]:
# Resumen técnico de tipos de datos y valores no nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

### ■ Paso 6: Estadísticos Descriptivos de Negocio
Calculamos la media, desvío estándar, mínimos, máximos y percentiles cuantitativos.

In [62]:
# Resumen de métricas de tendencia central y dispersión
pd.options.display.float_format = '{:.2f}'.format
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,54600.00,26.30,4.07,17.00,23.00,26.00,29.00,39.00
jersey_number,54600.00,13.50,7.50,1.00,7.00,13.50,20.00,26.00
height_cm,54600.00,181.65,6.28,163.00,177.00,182.00,186.00,200.00
weight_kg,54600.00,75.75,3.95,65.00,73.00,76.00,78.00,87.00
market_value_eur,54600.00,20084451.76,27188660.40,528822.00,4444778.00,10271107.00,23420128.00,200000000.00
...,...,...,...,...,...,...,...,...
total_goals_tournament,54600.00,0.64,1.09,0.00,0.00,0.00,1.00,10.00
total_assists_tournament,54600.00,0.61,0.93,0.00,0.00,0.00,1.00,8.00
total_minutes_tournament,54600.00,272.30,116.81,0.00,184.00,268.00,359.00,615.00
player_of_match_awards,54600.00,0.03,0.21,0.00,0.00,0.00,0.00,4.00
tournament_rating,54600.00,3.63,3.16,0.00,0.00,5.40,6.40,9.50

In [63]:
# Estadísticas descriptivas para variables cualitativas (texto)
df.describe(include='object').T

                  count unique                       top   freq
player_id         54600   1248                    P00957     66
player_name       54600   1245  Pierre-Emile Christensen     86
nationality       54600     48                    Qatari   1716
team              54600     48                     Qatar   1716
position          54600      4                  Defender  18900
preferred_foot    54600      2                     Right  40656
club_name         54600    122                 Gor Mahia    892
match_id          54600   1050                    M01050     52
match_date        54600     51                2026-06-30   1560
stadium           54600     16   Lincoln Financial Field   4264
city              54600     16              Philadelphia   4264
opponent_team     54600     48                     Qatar   1716
tournament_stage  54600      7               Group Stage  30056
match_result      54600      3                         W  20124